### ISSUE TITLE
【海外版】Linkedinのシェアボタンを追加する

### ISSUE THREAD

**Issue by dswebstudio** [kurudrive/biz-vektor#157]
現在どんなSNSを追加するかどうか選択できませんね。

日本じゃないとはてなブックマークが要らないかもしれません。
LINEは日本も含めてアジア圏の国だとあって良いでしょう（インドネシアなどでかなり普及されているため）。

アメリカなどでLinkedinというビジネス専用のSNSがあってヨーロッパでもけっこう使われています。
中国だとまた別のSNSですね。

BizVektor本体で修正するか、サードパーティプラグインに任せるか、対応しようとしたらいくつの方法があるんでしょうが。

**Comment by kurudrive** [comment]
Ex Unit で検討。本体には組み込まない。
