### ISSUE TITLE
トップページのスライダーの画像が出なくなった。

### ISSUE THREAD

**Issue by sk8erbird** [kurudrive/biz-vektor#174]
昨日から、トップページにあるスライドショーの画像が一切表示されなくなりました。
特に設定を変えたつもりはありません。
firefox・ie・ipadで確認しましたが白いままです。
（ipadだと、スライドショーの画像がすごく縦長の白い画像が出ています）

スライドショーの設定の画像ファイルが壊れたわけではありません。
設定の画像のアドレスを消すと、静止画でのトップ表示はされます

サーバーをsitemixというところにしており
もともと重いところではあるのですが、こういった現象は初めてです。

**Comment by kurudrive** [comment]
昨日BizVektorのバージョンを変更したのでしょうか？
変更したようでしたらいくつからいくつに変更したのかご連絡ください。

何も変更していないのに出なくなった場合はテーマとは別の所に原因があると思われます。

**Comment by sk8erbird** [comment]
昨日は変更してない状態で
現象が発生しており、サーバーも重くて
そのまま放っておいたのですが
古いバージョンだからかしら？と
インストール時のバージョンから、最新版に
アップデートを本日しましたが
サーバーの調子が良くなくて
アップデートが完全ではなかったのかも…。

一度テーマを削除して入れ直したほうが
いいのでしょうか？
テーマ削除したら、ページのデータとか
インフォメーションのデータは消えて無くなるのでしょうか？

**Comment by kurudrive** [comment]
ページのデータとかインフォメーションのデータはデータベースに保存されているので、テーマファイルを削除しても消えません。
一度テーマファイルを全て削除して入れなおした方が良いと思います。

**Comment by sk8erbird** [comment]
ありがとうございます。一度入れ直しを
試みてみます。
