### ISSUE TITLE
twitterからサイトを表示すると、「詳しくはこちら」ボタンが改行されてしまう

### ISSUE THREAD

**Issue by kasagi222labo** [kurudrive/biz-vektor#175]
現在、ver.1.6.0を使用しています。
現在作成したページ
http://yokkaichi-machicon.com
をtwitterのブラウザで開くと
Version 0.6.0.3での変更点の同じように
「詳しくはこちら」の「ら」が改行されてしまいます。

ほかのsmart phone、iphoneの各browserからは問題ありません。

**Comment by kurudrive** [comment]
↓下記と同様。対応済。
https://github.com/kurudrive/biz-vektor/issues/212
