### ISSUE TITLE
ajaxzip3の実装

### ISSUE THREAD

**Issue by honda3** [kurudrive/biz-vektor#192]
honda3と申します。

素人の域を出ませんが、BizVektor様のテンプレートを利用して少しずつカスタマイズ方法を勉強をさせて頂いています。
最近気がついたことがあり、要望として書き込みさせていただきます。

ajaxzip3を利用するには、header.phpにコードを貼り付ける必要がありますが、BizVektor本体にajaxzip3があればユーザーが貼り付ける必要はないのでは？と思った次第です。

不躾な要望で大変恐縮ですが、どうかご検討ください。

追記-----

よくよく考えてみますと、パソコンのIMEに郵便番号変換があり、スマホにも郵便番号から住所に変換できる機能もあるため、わざわざ実装することに意味のないことに気が付きました。

お騒がせして申し訳ございませんm(_ _)m

**Comment by kurudrive** [comment]
あぃ（・ｗ・；
