### ISSUE TITLE
Ver 1.7.4 がダウンロード出来ません

### ISSUE THREAD

**Issue by officegilberto** [kurudrive/biz-vektor#201]
いつも利用させていただいております。
ありがとうございます。

5/2現在、BizVektor Ver 1.7.4  がダウンロード出来ない状態のようです。
以下のページにあるボタンをクリックすると保存先のウィンドウが開き
ファイル名「biz-vektor_v_1_7_4.zip」となっていますが、
ネットワークエラーで保存出来ない状況です。

WindowsではIE、Chromeとも同じ状況ですが、
MacですとSafariのみダウンロードできるようです。

**Comment by rocket-martue** [comment]
こちらの環境では、特に問題なくダウンロードできています。
win8.1 Chrome、IE、FireFox　全てOKです。

http://bizvektor.com/about/download/
「biz-vektor_v_1_7_4.zip」

**Comment by kurudrive** [comment]
https://github.com/kurudrive/biz-vektor/issues/208
