### ISSUE TITLE
v1.7.6に更新したらTrust Formが表示されなくなった

### ISSUE THREAD

**Issue by Alessandro-mcbee** [kurudrive/biz-vektor#204]
バージョンアップし1.7.6にしたところ、Trust Formの項目が表示されなくなりました。
たぶんCSSの干渉が原因だと思いますが、他にも関係しているようで、簡単には修正できません。
不具合修正をお願いします。
またFacebook LikeBoxの左右のスペースも直してほしいです。

**Comment by kurudrive** [comment]
> バージョンアップし1.7.6にしたところ、Trust Formの項目が表示されなくなりました。

→ 表示されないというのはどういう状態でしょうか？
→ 使用しているデザインスキンは何でしょうか？

> またFacebook LikeBoxの左右のスペースも直してほしいです。

→ こちらはFacebookの仕様変更で新しいPagePlugin（LikeBox）は500px以上広くする事ができません。

**Comment by Alessandro-mcbee** [comment]
→ 表示されないというのはどういう状態でしょうか？
フォームフィールドの入力項目部分が表示されません。
http://www.lunetterie.jp/contact.html
こちらをご参照ください。
→ 使用しているデザインスキンは何でしょうか？
Rebuildです。

**Comment by Alessandro-mcbee** [comment]
レスポンシブのビューポイント周りで不具合が出ているかもしれません。
ブラウザ幅を狭くし、スマホサイズにすると問題なくフィールド項目が表示されました。

**Comment by rocket-martue** [comment]
<pre><code><</code>span class="content"<code>></code>項目<code><</code>/span<code>></code>
</pre>
の辺りが原因ですね。

カスタムcssに
<pre><code>#main #trust-form span.content { width: auto;　}</code></pre>
を記入してみてください。
フィールド項目が表示されると思います。

**Comment by Alessandro-mcbee** [comment]
表示されました。
素早いレスポンスに感謝します。

**Comment by kurudrive** [comment]
5289eae0324c09c4848cb0941edfa1e1d007b33d
