### ISSUE TITLE
本体のダウンロードについて

### ISSUE THREAD

**Issue by pegipegi1120** [kurudrive/biz-vektor#208]
本体のダウンロードができないようです。
以下のメッセージが表示されてしまいます。
/var/www/bizvektor.com/wp-content/plugins/download-manager/cache/ must have to be writable!

**Comment by kurudrive** [comment]
今確認した所問題なくダウンロード出来ますが、現在もまだ同じ症状でしょうか？

**Comment by chitaku503** [comment]
同じく以下のメッセージが表示されて本体のダウンロードができない事象となっています。
/var/www/bizvektor.com/wp-content/plugins/download-manager/cache/ must have to be writable!

**Comment by kurudrive** [comment]
ブラウザは何をご利用でしょうか？
他のブラウザでもダウンロード出来ないでしょうか？

**Comment by rocket-martue** [comment]
Win 8.1で、午前中は、Chrome　IE　共に同様のメッセージ
/var/www/bizvektor.com/wp-content/plugins/download-manager/cache/ must have to be writable!
が出ていましたが、今は問題なくダウンロードできています。
