### ISSUE TITLE
Facebook PagePlugin（旧LikeBox）のウィジェット復活

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/biz-vektor#209]

**Comment by kurudrive** [comment]
処理待ち

**Comment by magonote** [comment]
お世話になっております。
早々に復活していただいたのに、検証する時間がなく・・・中身が復活していないのではないでしょうか？
ウィジェットを入れても何も表示されません^^;

**Comment by kurudrive** [comment]
お待たせしました。修正しました。
https://github.com/kurudrive/biz-vektor/commit/27c7056c786085966aa5618012ac4448f13b5df1
