### ISSUE TITLE
WorksUnitで登録した情報の作成者を変更できない

### ISSUE THREAD

**Issue by issi0128** [kurudrive/biz-vektor#211]
WorksUnitで、登録した情報の作成者を変更することが出来ません。
変更できるようにならないでしょうか。

管理者がまとめて登録して、あとから編集者が修正・・・と思っても、現状では出来なくて不便です。
ご検討のほどよろしくお願いします。

**Comment by issi0128** [comment]
失礼しました。DLmarketの質問よりご連絡します。

**Comment by kurudrive** [comment]
確認・修正中です。
今しばらくお待ちください。

**Comment by issi0128** [comment]
早々の対応ありがとうございます。
先ほど入れ換えて確認致しました。
