### ISSUE TITLE
BV_最近の投稿 ウィジェットでカテゴリーを指定可能にする

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/biz-vektor#213]
ウィジェットの設定で、テキストフィールドにカテゴリーのIDを数字で入力出来るようにする。
入力がある場合はそのカテゴリーでも絞り込んだ結果を表示する。

ExUnitも同様に対応
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/issues/45

**Comment by nc30** [comment]
a67d464f7141622d377bb67dcf455f18c7098b73

**Comment by kurudrive** [comment]
ありがとうございます -> nc30
