### ISSUE TITLE
検索結果表示ページのPC画面表示で、検索実行ボタンが下にずれて表示されます

### ISSUE THREAD

**Issue by c-isogai** [kurudrive/biz-vektor#240]
バージョン1.8.11 Calmlyにて
検索結果表示ページのPC画面表示で、
検索キーワード入力欄横に来るはずの検索実行ボタンが、下にずれて表示されます。
スマホ用表示は問題ありません。

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
修正しました。リリースまで今しばらくお待ちください。
