### ISSUE TITLE
有償の拡張デザインスキンrefineが表示されません（プラグインインストール済）

### ISSUE THREAD

**Issue by picotan555** [kurudrive/biz-vektor#242]
フォーラムの質問を探したのですが、見当たらなかったため質問させていただきます。
問題発覚の流れは以下のとおりです。
１．有償の拡張デザインスキンrefineを購入後ダウンロード、プラグインとしてインストールし、設定完了しました。有効化されています。
２．その後、WPのテーマにbizvektorをダウンロードしテーマとして設定しました。（現在のテーマはbizvektorと表示されている）
３．それから、WP＞外観＞BizVektor テーマオプション＞デザイン＞デザインの設定からデザインスキンの項目でrefine　をプルダウンで選択しましたが、無料版のスキンデザインが表示されており、relineのデザインが出ない状況です。
すみませんが、お教えいただけるとありがたく存じます。
有償版を買ったのは、デザインだけでなく、無償版よりはきちんとしたサポート窓口があるのかと思っていたのですが・・・・。もし不具合でしたら購入をキャンセルしなければならず困っております。よろしくおねがいいたします。

**Comment by kurudrive** [comment]
プラグイン Headcleaner が有効化されていないでしょうか？

そうでなければ一度症状を確認したいので
DLmarketの商品ページの「カートに入れる」ボタンの下に、販売者への問い合わせがありますので、
そちらから該当URLと管理画面へのログイン情報をご連絡ください。

以上よろしくお願いいたします。
