### ISSUE TITLE
BizVektor FooterPowerdDeleteが機能しない

### ISSUE THREAD

**Issue by tairai** [kurudrive/biz-vektor#244]
お布施のつもりでBizVektor FooterPowerdDeleteを購入しましたがプラグインを有効化しても反映されません。起こり得る原因としては何があるのでしょうか。
![001](https://cloud.githubusercontent.com/assets/16695302/12313675/11674c00-baad-11e5-9071-680c847943fa.jpg)
![002](https://cloud.githubusercontent.com/assets/16695302/12313676/11c6d8a0-baad-11e5-8710-4e1f812fef02.jpg)

**Comment by kurudrive** [comment]
利用中のBizVektorはBizVektor公式サイトからダウンロードしてアップしたBizVektorでしょうか？
管理画面から直接インストール出来る「BizVektor Global Edition」は機能が制限された（WordPress公式ディレクトリにアップするために制限せざるをえなかった）簡易版なのでFooter Powered Delete は動作しません。
下記のフル機能版をお試しください。
http://bizvektor.com/about/download/

**Comment by tairai** [comment]
ありがとうございます。解決しました。

**Comment by tairai** [comment]
ありがとうございます。解決しました。

> 利用中のBizVektorはBizVektor公式サイトからダウンロードしてアップした 
> BizVektorでしょうか？
> 管理画面から直接インストール出来る「BizVektor Global Edition」は機能が 
> 制限された（WordPress公式ディレクトリにアップするために制限せざるをえ 
> なかった）簡易版なのでFooter Powered Delete は動作しません。
> 下記のフル機能版をお試しください。
> http://bizvektor.com/about/download/
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kurudrive/biz-vektor/issues/244#issuecomment-171501297>.
>


-- 
-----------------------------------
アド・デザイン  平井 伸明
TEL 0868-22-7607 / FAX 0868-22-7621
mail: n-hirai@net-ad.co.jp
