### ISSUE TITLE
Grid Unit最新版

### ISSUE THREAD

**Issue by sevenseconds777** [kurudrive/biz-vektor#256]
DLマーケットよりアップグレード案内がきたのでGrid Unit最新版を使用してみたところ
管理画面やウィジェットにGrid Unit項目が出ませんでした。
本体やテーマプラグインのバージョンの問題かとおもい、最新版に変えましたが、出ませんでした。
昔のGrid Unitを入れなおし使用しています。

VASTというテーマプラグインとの併用です。

**Comment by kurudrive** [comment]
確認しましたが弊社環境では症状が確認できませんでしたので該当のURLをこちらに貼る事は出来ますでしょうか？
まずいようでしたら、DLmarketにログインの上
http://www.dlmarket.jp/products/detail/285023
に非公開で投稿いただければとおもいます。
よろしくお願いいたします。
