### ISSUE TITLE
「Graceful」が反映出来ない

### ISSUE THREAD

**Issue by shinzee** [kurudrive/biz-vektor#258]
「Graceful」を購入いたしました。

WordPressのダッシュボードより外観設定にてBizVekorを設定し
プラグインより「Graceful」をインストールし、続いてTipsに従って
BizVekorのデザイン選択プルダウンより 「Graceful」を選択しようと試みましたが
プルダウンメニューが出てきません。

どのようにしたら「Graceful」をBizVekorに反映出来ますでしょうか。

手順をお知らせください。

**Comment by kurudrive** [comment]
ご購入ありがとうございます。
まず 
* Gracefulが有効化されているかどうか？
* BizVektor のバージョンが古くないかどうか？
* BizVektorがGlobal Editionを使用していないかどうか？
  （WordPress公式ディレクトリのGlobal Edition ではなくbizvektor.comで配布している通常版用です）
をご確認下さい。

**Comment by shinzee** [comment]
kurudrive さま

お知らせいただきましたTipsにありましたGlobal Editionを設定していたためインストール出来なかったことが判明いたしました。通常版インストールの後、プラグイン設定にてGracefulが反映出しました。

Gracefulの商品説明ページにGlobal Editionからは設定出来ない旨の記載があるべきではないでしょうか。
問い合わせもgithubでしか出来ないし、苦言を呈するようで恐縮ですが、有償にてデリバリーしているにも関わらず、ユーザーフレンドリーではないと思いました。改善されることを望みます。

**Comment by kurudrive** [comment]
ご連絡ありがとうございます。
Global Edition から設定出来ない旨追記させていただきました。
ご指摘ありがとうございます。
今後ともBizVektorをよろしくお願いいたします。

**Comment by shinzee** [comment]
kurudrive さま

早々にご対応いただき、感謝いたします。
取り急ぎ御礼まで。
