### ISSUE TITLE
新規投稿を追加/新規固定ページを追加のメタキーワード欄にWarning

### ISSUE THREAD

**Issue by arborvitae666** [kurudrive/biz-vektor#268]
新規投稿を追加/新規固定ページを追加のメタキーワード欄に
Warning: call_user_func() expects parameter 1 to be a valid callback, function 'insert_custom_field_metaKeyword' not found or invalid function name in /wp-admin/includes/template.php on line 1045
と出力されます。
/biz-vektor/plugins/seo_and_ga/seo_and_ga.phpの
58行目のfunction insert_custom_field_metawKeyword()と
関数名が変更されたのが原因ではないでしょうか?

BizVektor 1.9.4

**Comment by kurudrive** [comment]
対応いたしました。ご報告ありがとうございました。
公式サイトには修正版をアップいたしました。
自動アップデートは本日中に反映されると思いますので、今暫くお待ちください。
ご迷惑をおかけして恐縮ですがよろしくお願いいたします。
